apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-chatbot
  labels:
    app: health-chatbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-chatbot
  template:
    metadata:
      labels:
        app: health-chatbot
    spec:
      containers:
      - name: chatbot-api
        image: health-chatbot:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/health_chatbot"
        - name: WHATSAPP_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: whatsapp-token
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: twilio-sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: twilio-token
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: health-chatbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secrets
type: Opaque
data:
  whatsapp-token: <base64-encoded-token>
  twilio-sid: <base64-encoded-sid>
  twilio-token: <base64-encoded-token>
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chatbot-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-chatbot
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
